### ISSUE TITLE
Graficas variabilidad radiación

### ISSUE THREAD

**Issue by ClaudiaGEscribano** [REuclmupm/pruebas#1]
Código para la elaboración de las dos gráficas principales de variabilidad de recurso:
- Media anual de CV y radiacion: por clusters  y con las medias de la Península superpuestas.
  El código está en **[cuadranteAnual.R](https://github.com/REuclmupm/pruebas/blob/master/cuadranteAnual.R)**
  Esta gráfica está hecha, pero podría darse una vuelta.
- Para la gráfica del ciclo anual de CV el código está en **[graphsCVinteranual_sat.R](https://github.com/REuclmupm/pruebas/blob/master/graphsCVinteranual_sat.R)**
  En la parte final del código intento manipular los datos para hacer una gráfica tipo boxplot o violinplot  del ciclo anual para cada cluster.

**Comment by oscarperpinan** [comment]
Recibido. Me pongo con ello durante estos días.

**Comment by oscarperpinan** [comment]
He modificado cuadranteAnual.R para mejorar un poco el scatterplot, pero lo importante es que he añadido mapas a partir de las definiciones de cluster.
Con graphsCVinteranual_sat.R he podido hacer muy poco porque me lío con las fuentes de datos. Tenemos que hablar sobre la organización de los ficheros.

**Comment by ClaudiaGEscribano** [comment]
Recibido. 
Me gusta mucho la representación del CV con mapas, muy visual y llamativo el resultado del cluster 11. Anoche pude correr el código en el ordenador de la upm.La he añadido a la presentación. :)

No me extraña que no hayas podido hacer nada para graphsCVinteranual_sat.R. Está todo bastante desordenado. Voy dándole una vuelta, ordenando y eliminando datos que no hagan falta y vamos hablando.

**Comment by ClaudiaGEscribano** [comment]
Estoy teniendo problemas con Git a la hora de subir los cambios desde mi local a este remoto.

Quería dejar en el repositorio únicamente lo fundamental para éstas últimas gráficas y no lo consigo.  Git lfs me da problemas, ya me paso una vez y no conseguí solucionarlo. Estoy un poco bloqueada, no sé si eliminar este remoto directamente y crear uno nuevo.

**Comment by ClaudiaGEscribano** [comment]
¿Te parece que cierre este issue? Ahora en el repositorio article_vari está todo el código que necesitamos o estará el que vayamos a crear. Los datos, lo que hemos hablado, en el ordenador upm. Abrimos otro allí para ir avanzando.

**Comment by oscarperpinan** [comment]
Hecho :-)
